/* ===================================================
 * dtooltip.js v0.5
 * ===================================================
 * Copyright 2012 Kim Lindhardt Madsen
 *
 * TODO find a license
 * ========================================================== */
(function(h){function s(a){return"function"==typeof a?s(a()):a}function t(a,c,d,g,n){var b,f=a[0].ownerDocument;h.dTooltip.dynamicStyle||(b=f.getElementsByTagName("head")[0],f=f.createElement("style"),f.type="text/css",b.appendChild(f),h.dTooltip.dynamicStyle=f);b=h.dTooltip.dynamicStyle;var k;b.styleSheet&&(k=b.styleSheet);b.sheet&&(k=b.sheet);var j;if(180===c)c="Top",b="Bottom",f="Right",j=a.width()/2;else if(90===c)c="Left",b="Right",f="Bottom",j=a.height()/2;else if(0===c||360===c)c="Bottom",
b="Top",f="Left",j=a.width()/2;else if(270===c)c="Right",b="Left",f="Top",j=a.height()/2;else throw"angle is not supported";a.css("-webkit-touch-callout","none").css("-webkit-user-select","none").css("-khtml-user-select","none").css("-moz-user-select","none").css("-ms-user-select","none").css("user-select","none");var l,p,e,q;if(n){l=a[0].ownerDocument;var m=h(l.createElement("div"));m.addClass(g).addClass("hover");h(l.body).append(m);l=parseInt(m.css("border"+c+"Width"),10);p=m.css("border"+c+"Color");
e=m.css("border"+c+"Style");q=m.css("backgroundColor");m.remove()}else l=parseInt(a.css("border"+c+"Width"),10),p=a.css("border"+c+"Color"),e=a.css("border"+c+"Style"),q=a.css("backgroundColor");l||(l=0,p=q);if(!e||"none"===e)e="solid";a="#"+a.attr("id");m=a+"."+g;n&&(m+=".hover");(this.afterRule=u(k,m+":after"))&&v(this.afterRule.style,c,b,f,d-l,e,d-l,q,j);g=a+"."+g;n&&(g+=".hover");(this.beforeRule=u(k,g+":before"))&&v(this.beforeRule.style,c,b,f,d,e,d,p,j-l);return[this.beforeRule,this.afterRule]}
function v(a,c,d,g,h,b,f,k,j){a.borderWidth=h+"px";a.borderColor="transparent";a.borderStyle=b;a["border"+c+"Width"]="0px";a["border"+d+"Width"]=f+"px";a["border"+d+"Color"]=k;a.position="absolute";a.height="0";a.width="0";a[d.toLowerCase()]="100%";a[g.toLowerCase()]=j+"px";a.display="inline-block";try{a.content='""'}catch(l){}}function u(a,c){var d=w(a,c);if(d)return d;a.addRule?a.addRule(c):a.insertRule&&a.insertRule(c+"{}",0);return w(a,c)}function w(a,c){var d=a.cssRules?a.cssRules:a.rules;if(d)for(var g=
0;g<d.length;g++){var h=d[g];if(h.selectorText&&h.selectorText.toLowerCase().replace(/:/g,"")==c.toLowerCase().replace(/:/g,""))return h}return null}h.extend({dTooltip:{version:0.5,defaults:{angle:180,cssClass:"dtooltip",spacing:5,offset:{top:0,left:0},content:"<p>Insert html</p>",showEvent:"mouseenter",hideEvent:"mouseleave",showDelay:0,hideDelay:0}}});h.fn.extend({dTooltip:function(a){function c(){var a=$(n),c=b.spacing;b.arrowSize&&(c+=b.arrowSize);var e=f,d=b.angle,h=b.offset;if(360<d||0>d)throw"You have misconfigured the tooltip - please choose from an angle between 0-360 degrees for the object: #"+
a.attr("id");var g=a.offset(),j,k,r;j=a.width()+(a.outerWidth()-a.width());a=a.height()+(a.outerWidth()-a.width());k=e.width()+(e.outerWidth()-e.width());r=e.height()+(e.outerWidth()-e.width());e=[];if(0===d||360===d)e[0]=g.left+Math.round(j/2)-Math.round(k/2),e[1]=g.top-(r+c);else if(90===d)e[0]=g.left+j+c,e[1]=g.top+Math.round(a/2-r/2);else if(180===d)e[0]=g.left+Math.round(j/2)-Math.round(k/2),e[1]=g.top+a+c;else if(270===d)e[0]=g.left-(k+c),e[1]=g.top+Math.round(a/2-r/2);else throw"angle is not at this time";
e[0]+=h.left;e[1]+=h.top;d=f;c=e[0];h=e[1];d.css("position","absolute");d.css("top",h);d.css("left",c)}function d(){c();b.show?b.show(f):f.fadeIn(200)}function g(){b.remove?b.hide(f):f.fadeOut(200)}var n=this,b=h.extend({},h.dTooltip.defaults,a);a="dTooltip_"+this.attr("id");var f=h(document.createElement("div")).html(s(b.content)).addClass(b.cssClass).attr("id",a).css("display","none");h(document.body).append(f);var k=!1,j=!1;b.showEvent&&this.bind(b.showEvent,function(){j=!1;k=!0;window.setTimeout(function(){j||
d()},b.showDelay)});b.hideEvent&&this.bind(b.hideEvent,function(){j=!0;k=!1;window.setTimeout(function(){k||g()},b.hideDelay)});this.hover(function(){$(f).addClass("hover")},function(){$(f).removeClass("hover")});b.arrowSize&&(t(f,b.angle,b.arrowSize,b.cssClass),t(f,b.angle,b.arrowSize,b.cssClass,!0));return{element:f,reposition:c,reveal:d,hide:g,remove:function(){f.remove()}}}})})(jQuery);